---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: {{.Values.env}}
    io.kompose.service: crocodile-{{.Values.env}}
    tier: backend
  name: crocodile-{{.Values.env}}
spec:
  ports:
    - name: "8080"
      protocol: TCP
      port: 8080
    - name: "9999"
      protocol: TCP
      port: 9999
  selector:
    io.kompose.service: backend
