---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yml -o kubernetes -c
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    environment: {{.Values.env}}
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-prod.yml -o kubernetes -c
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        environment: {{.Values.env}}
        io.kompose.service: redis
        name: redis
    spec:
      containers:
      - name: redis
        image: bitnami/redis:latest
        ports:
        - containerPort: 6379
        env:
        - name: ALLOW_EMPTY_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: ALLOW_EMPTY_PASSWORD
              name: env
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/redis/data
          name: crocodile-redis-volume
      - name: redis-exporter
        image: oliver006/redis_exporter:alpine
        ports:
        - containerPort: 9121
        env:
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              key: REDIS_ADDR
              name: env
        - name: REDIS_EXPORTER_WEB_TELEMETRY_PATH
          valueFrom:
            configMapKeyRef:
              key: REDIS_EXPORTER_WEB_TELEMETRY_PATH
              name: env
        resources: {}
      nodeSelector:
        kubernetes.io/hostname: {{.Values.redisNodeSelectorHostname}}
      volumes:
      - name: crocodile-redis-volume
        hostPath:
          path: {{.Values.redisHostPath}}
          type: DirectoryOrCreate
      restartPolicy: Always
status: {}
